spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
  #    url: jdbc:mysql://39.107.237.117:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #    password: 222222

  rabbitmq:
    username: guest
    password: guest
    #    host: 39.107.237.117
    host: 127.0.0.1
    #    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        prefetch: 1 # 每个消费者每次可以消费一个
  redis:
    #    host: 39.107.237.117
    host: 127.0.0.1
    database: 0
    port: 6379
  #    password: 123
  cache:
    cache-names: menus_cache2
  devtools:
    restart:
      #热部署生效(true为开启，false为不开启，开发者根据喜好选择是否开启)
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      exclude: WEB-INF/**
server:
  port: 8012
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://39.107.237.117/


  # 此处配置在启动主程序时加载
Spring:
  flyway:
    # 是否启用flyway    true  false
    enabled: false
    ## 编码格式，默认UTF-8
    encoding: UTF-8
    ## 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:db/migration
    ## 迁移sql脚本文件名称的前缀，默认V
    sqlMigrationPrefix: V
    ## 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sqlMigrationSeparator: __
    # 迁移sql脚本文件名称的后缀
    sqlMigrationSuffixes: .sql
    # 迁移时是否进行校验，默认true
    validateOnMigrate: true
    # 设置为true，当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baselineOnMigrate: true
    # postgres10没有引入这个不提示错误，postgres12没有引入会报错
    schemas: jooq

